# Generated by Django 5.2.10 on 2026-01-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stokc',
            new_name='stock',
        ),
    ]
