# Generated by Django 5.2.10 on 2026-01-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
