# Generated by Django 5.2.10 on 2026-05-01 14:58

import product.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/', validators=[product.validate.validate_file_size]),
        ),
    ]
